version: '3.7'

services:
  xlsx2influxdb:
    image: "registry.gitlab.whiteaster.com/openforestdata/backend/xlsx2influxdb:feature-working-influx-uploader"
    container_name: "xlsx2influxdb"
    restart: unless-stopped
    environment:
      - DBNAME=data
      - SQLITE_DB_NAME=data
      - INPUT=/app/Bialowieza_2021.txt
      - TIMECOLUMN=date
      - SERVER=172.17.0.1:8086
      - TIME_SECCONDS=600
    volumes:
      - "./Bialowieza_2021.txt:/app/Bialowieza_2021.txt"
    networks:
      - influx_grafana

networks:
  influx_grafana:
