version: '3.7'

services:
  xlsx2influxdb:
    image: "registry.gitlab.whiteaster.com/openforestdata/backend/xlsx2influxdb:latest"
    container_name: "xlsx2influxdb"
    restart: unless-stopped
    environment:
      - DBNAME=data
      - SQLITE_DB_NAME=data
      - INPUT=/app/dane_meteo.xlsx
      - TIMECOLUMN=data/godzina
      - SERVER=localhost:8086
      - TIME_SECCONDS=60
    volumes:
      - "./dane_meteo_2011_05_Bialowieza.xlsx:/app/dane_meteo.xlsx"
    networks:
      - influx_grafana

networks:
  influx_grafana:
